# Generated by Django 2.2.5 on 2019-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.IntegerField()),
                ('Nombre', models.TextField(max_length=125)),
                ('Password', models.TextField(max_length=125)),
                ('Correo', models.TextField(max_length=125)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
