# Generated by Django 2.2.5 on 2019-09-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muelitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('1', 'secretaria'), ('2', 'odontologo'), ('3', 'paciente')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Documento',
            field=models.BigIntegerField(),
        ),
    ]
