# Generated by Django 2.2.4 on 2019-09-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muelitas', '0002_auto_20190913_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='estado',
            new_name='Estado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('1', 'secretaria'), ('2', 'odontologo'), ('3', 'paciente')], default='3', max_length=1),
        ),
    ]
