# Generated by Django 2.2.4 on 2019-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muelitas', '0003_auto_20190925_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Documento',
            field=models.BigIntegerField(unique=True),
        ),
    ]
